# Generated by Django 5.2.6 on 2025-09-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.IntegerField(default=0),
        ),
    ]
